### ISSUE TITLE
Cannot read property 'isTTY' of undefined

### ISSUE THREAD

**Issue by aeosynth** [jashkenas/coffeescript#1078]
I just upgraded to node v0.3.6, and when I run `coffee`, I get this error:

```
TypeError: Cannot read property 'isTTY' of undefined
    at new Interface (readline.js:37:24)
    at Object.createInterface (readline.js:17:10)
    at Object.<anonymous> (/home/james/.node_libraries/.npm/coffee-script/1.0.0/package/lib/repl.js:32:19)
    at Object.<anonymous> (/home/james/.node_libraries/.npm/coffee-script/1.0.0/package/lib/repl.js:42:4)
    at Module._compile (node.js:423:30)
    at Object..js (node.js:429:14)
    at Module.load (node.js:355:35)
    at Function._load (node.js:322:14)
    at require (node.js:367:23)
    at Object.run (/home/james/.node_libraries/.npm/coffee-script/1.0.0/package/lib/command.js:45:14)
```

I think I still get into the coffee repl, because commands I type aren't interpreted by my shell, and when I hit ^D I return to my normal prompt.

the `node` repl works fine.

edit: downgrading to node v0.3.5 fixes this.

**Comment by 1j01** [comment]
For anyone googling this error message, [`readline.createInterface`](https://nodejs.org/api/readline.html#readline_readline_createinterface_options) will try to check `output.isTTY` if you don't specify `terminal`, so if you aren't specifying an `output`, you need to explicitly specify `terminal` on some versions of node. Node v0.12.0 doesn't seem to be effected, but v0.10.38 does.
```js
readline.createInterface({terminal: false, input: someStream});
```
