### ISSUE TITLE
Cannot use a pure statement in an expression error doesn't include line info

### ISSUE THREAD

**Issue by kpdecker** [jashkenas/coffeescript#1361]
The error produced by compiling the code listed below does not provide any context information for debugging. Without this is quite difficult to debug.

```
  foo = (len) ->
    test = [0..10]
    y = for x in test
      if x > 5
        return false
      else
        x
    y
```

```
SyntaxError: In test.coffee, cannot use a pure statement in an expression.
    at SyntaxError (unknown source)
    at For.compileClosure (/Users/kdecker/.node_libraries/.npm/coffee-script/1.0.1/package/lib/nodes.js:45:15)
    at For.compile (/Users/kdecker/.node_libraries/.npm/coffee-script/1.0.1/package/lib/nodes.js:40:21)
    at Assign.compileNode (/Users/kdecker/.node_libraries/.npm/coffee-script/1.0.1/package/lib/nodes.js:1110:24)
    at Assign.compile (/Users/kdecker/.node_libraries/.npm/coffee-script/1.0.1/package/lib/nodes.js:38:21)
    at Block.compileNode (/Users/kdecker/.node_libraries/.npm/coffee-script/1.0.1/package/lib/nodes.js:254:23)
    at Block.compileWithDeclarations (/Users/kdecker/.node_libraries/.npm/coffee-script/1.0.1/package/lib/nodes.js:302:19)
    at Code.compileNode (/Users/kdecker/.node_libraries/.npm/coffee-script/1.0.1/package/lib/nodes.js:1343:35)
    at Code.compile (/Users/kdecker/.node_libraries/.npm/coffee-script/1.0.1/package/lib/nodes.js:38:21)
    at Assign.compileNode (/Users/kdecker/.node_libraries/.npm/coffee-script/1.0.1/package/lib/nodes.js:1110:24)
```

**Comment by johndeighan** [comment]
I think you probably should consider rewriting the parser. What I found was that this *.coffee file compiles and runs just fine using the `coffee `command:
```
count = 5
x = (() ->
	double = 2 * count
	console.log "Count is #{count}"
	return 23
	)()
console.log "x = #{x}"
```
while this, when compiled using `CoffeeScript.compile(text, {bare: true})` fails with the error in this post:

```
x = (() ->
         double = 2 * count
        console.log "Count is #{count}"
        return 23
        )()
```

Something is clearly amiss.

**Comment by edemaine** [comment]
@johndeighan That is how indentation-based languages work (same with Python).  In your second example, the lexer emits an OUTDENT token before `console.log`. You can see this if you run `coffee --tokens filename.coffee`. Admittedly, the error message could be clearer, but as originally mentioned, this is hard to fix.
