### ISSUE TITLE
repl.js broken in HEAD?

### ISSUE THREAD

**Issue by ghost** [jashkenas/coffeescript#3395]
Hi,
I'm running a fairly fresh install of Linux Mint Debian Edition. I've manually compiled node and npm from their respective git repos, and have just D/L'd coffee-script from this git repo. So, everything is as fresh as can be!

I've had some bugs with npm itself, where it was installing outdated required libs and kept complaining when I'd try to use bin/cake that it couldn't find underscore.. telling npm to update fixed that issue, thankfully.

Now, bin/cake is working, but tests fail, and I still have a persistent problem with bin/coffee, though. Running coffee, I get this: 

```
me@localhost ~/locallib/coffee-script $ git pull
Already up-to-date.
me@localhost ~/locallib/coffee-script $ bin/coffee
coffee> /home/cathal/locallib/coffee-script/lib/coffee-script/repl.js:48
      initialPrompt: repl.prompt.replace(/^[^> ]*/, function(x) {
                                 ^
TypeError: Object function (preserveCursor) {
  if (this.paused) this.resume();
  if (this.terminal) {
    if (!preserveCursor) this.cursor = 0;
    this._refreshLine();
  } else {
    this.output.write(this._prompt);
  }
} has no method 'replace'
  at addMultilineHandler (/home/cathal/locallib/coffee-script/lib/coffee-script/repl.js:48:34)
  at Object.module.exports.start (/home/cathal/locallib/coffee-script/lib/coffee-script/repl.js:155:7)
  at Object.exports.run (/home/cathal/locallib/coffee-script/lib/coffee-script/command.js:79:32)
  at Object.<anonymous> (/home/cathal/locallib/coffee-script/bin/coffee:7:41)
  at Module._compile (module.js:449:26)
  at Object.Module._extensions..js (module.js:467:10)
  at Module.load (module.js:349:32)
  at Function.Module._load (module.js:305:12)
  at Function.Module.runMain (module.js:490:10)
  at startup (node.js:124:16)
  at node.js:803:3
```

Running bin/cake build:all, I get this:

```
failed 3 and passed 548 tests in 9.97 seconds 

  CoffeeScript.eval can run in, and modify, a Script context sandbox 
  TypeError: Object function ContextifyScript() { [native code] } has no method 'createContext'
  at Function.<anonymous> (/home/cathal/locallib/coffee-script/test/eval.coffee:13:25)
  at global.test (/home/cathal/locallib/coffee-script/Cakefile:275:12)
  at Object.<anonymous> (/home/cathal/locallib/coffee-script/test/eval.coffee:12:3)
  at Object.<anonymous> (/home/cathal/locallib/coffee-script/test/eval.coffee:1:1)
  at Module._compile (module.js:449:26)

  function () {
      var code, result, sandbox;
      sandbox = vm.Script.createContext();
      sandbox.foo = 'bar';
      code = 'global.foo = \'not bar!\'';
      result = CoffeeScript["eval"](code, {
        sandbox: sandbox
      });
      eq(result, 'not bar!');
      return eq(sandbox.foo, 'not bar!');
    }

  CoffeeScript.eval can run in, but cannot modify, an ordinary object sandbox 
  TypeError: Object function ContextifyScript() { [native code] } has no method 'createContext'
  at Object.exports.eval (/home/cathal/locallib/coffee-script/lib/coffee-script/coffee-script.js:133:47)
  at Function.<anonymous> (/home/cathal/locallib/coffee-script/test/eval.coffee:27:14)
  at global.test (/home/cathal/locallib/coffee-script/Cakefile:275:12)
  at Object.<anonymous> (/home/cathal/locallib/coffee-script/test/eval.coffee:22:3)
  at Object.<anonymous> (/home/cathal/locallib/coffee-script/test/eval.coffee:1:1)
  at Module._compile (module.js:449:26)

  function () {
      var code, result, sandbox;
      sandbox = {
        foo: 'bar'
      };
      code = 'global.foo = \'not bar!\'';
      result = CoffeeScript["eval"](code, {
        sandbox: sandbox
      });
      eq(result, 'not bar!');
      return eq(sandbox.foo, 'bar');
    }

  TypeError: Object function (preserveCursor) {
  if (this.paused) this.resume();
  if (this.terminal) {
    if (!preserveCursor) this.cursor = 0;
    this._refreshLine();
  } else {
    this.output.write(this._prompt);
  }
} has no method 'replace'
  at addMultilineHandler (/home/cathal/locallib/coffee-script/lib/coffee-script/repl.js:48:34)
  at Object.module.exports.start (/home/cathal/locallib/coffee-script/lib/coffee-script/repl.js:155:7)
  at testRepl (/home/cathal/locallib/coffee-script/test/repl.coffee:37:15)
  at Object.<anonymous> (/home/cathal/locallib/coffee-script/test/repl.coffee:43:1)
  at Object.<anonymous> (/home/cathal/locallib/coffee-script/test/repl.coffee:1:1)
  at Module._compile (module.js:449:26)
```

Any ideas? :-/

**edit by @michaelficarra:**  cleaned up formatting

**Comment by joehakimrahme** [comment]
I still have the same problem with node `0.12.0` and coffee `1.7.1` installed with npm.

`npm install -g http://github.com/jashkenas/coffeescript/tarball/master` didn't fix it.

**Comment by ognus** [comment]
@joehakimrahme I got the same problem after updating to node `0.12.0`. Using coffee `1.7.1`

**Comment by skrat** [comment]
Same here

**Comment by jammi** [comment]
Same again, at node v5.4.1, coffee v3.0.3

**Comment by bepetersn** [comment]
For posterity... Had this same problem just now. Updating coffeescript via @joehakimrahme above did fix it.

**Comment by dwy6626** [comment]
same here with node 14 and coffee 2.7.0

**Comment by snowman** [comment]
> I'm not sure it's the better solution, I just change `prompt` to `_prompt` in the following lines:
> 
> ```
> -    initialPrompt: repl.prompt.replace /^[^> ]*/, (x) -> x.replace /./g, '-'
> -    prompt: repl.prompt.replace /^[^> ]*>?/, (x) -> x.replace /./g, '.'
> +    initialPrompt: repl._prompt.replace /^[^> ]*/, (x) -> x.replace /./g, '-'
> +    prompt: repl._prompt.replace /^[^> ]*>?/, (x) -> x.replace /./g, '.'
> ```

This works for me

```sh
$ coffee --version
CoffeeScript version 1.6.3

$ nvm --version
0.39.1

$ node --version
v4.9.1
```
