### ISSUE TITLE
source maps only work for files ending in `.coffee`

### ISSUE THREAD

**Issue by roman-neuhauser** [jashkenas/coffeescript#3413]
```
1033:0 > cat fubar.coffee
console.log 'hello world!'
throw new Error 'omg wtf!

1034:0 > coffee fubar.coffee
hello world!
Error: omg wtf!
  at Object.<anonymous> (/home/.../fubar.coffee:2:11)
  at Object.<anonymous> (/home/.../fubar.coffee:1:1)
  at Module._compile (module.js:456:26)

1035:1 > mv fubar.coffee fubar

1036:0 > coffee fubar
hello world!
Error: omg wtf!
  at Object.<anonymous> (/home/.../fubar:4:9)
  at Object.<anonymous> (/home/.../fubar:6:4)
  at Module._compile (module.js:456:26)

1037:1 > coffee --version
CoffeeScript version 1.7.1
```

**Comment by GeoffreyBooth** [comment]
Seems to have been fixed:

```sh
$ coffee fubar
hello world!
Error: omg wtf!
    at Object.<anonymous> (./fubar:2:7)
    at Object.<anonymous> (./fubar:1:1)
```
