### ISSUE TITLE
use sourceMaps with register()

### ISSUE THREAD

**Issue by timaschew** [jashkenas/coffeescript#3541]
The register function has a hardcoded `false` value for sourceMap. I tried to set it to true, but then I get this error:

```
module.js:377
  content = content.replace(/^\#\!.*/, '');
                    ^
TypeError: Object #<Object> has no method 'replace'
  at Module._compile (module.js:377:21)
  at Object.loadFile (/Users/awilhelm/dev/codo/bin/register.js:16:19)
  at Module.load (/Users/awilhelm/dev/codo/bin/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/Users/awilhelm/dev/codo/bin/codo:13:1)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at [object Object].Module.runMain [as _onTimeout] (module.js:497:10)
  at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```

Wjhy it's not possible to use sourceMap for this case?
https://github.com/jashkenas/coffeescript/blob/master/lib/coffee-script/register.js#L15

**Comment by aleclarson** [comment]
+1

**Comment by GeoffreyBooth** [comment]
There’s no way to set options via `register`. For this kind of control, you should use a full-fledged build tool, like Browserify or Webpack. With those, and modules via `require` or `import`, you can get source maps in Node apps that use modules.
