### ISSUE TITLE
Yield operator doesn't works properly with extends statement.

### ISSUE THREAD

**Issue by yetanotherusernamebecausegithubisbugged** [jashkenas/coffeescript#3666]
It looks like yield operator doesn't works properly with extends statement.

``` coffeescript
co = require 'co'
fs = require 'mz/fs'

class A

  constructor: ->
    @exists = yield fs.exists('/etc/passwd')
    console.log "A.exists: #{@exists}"

class B extends A

  constructor: ->
    yield super()

  printExists: ->
    console.log "B.exists: #{@exists}"

do co ->
  a = yield new A()
  b = yield new B()
  b.printExists()
```

Results in:

```
$ coffee test51.coffee 
Running node v0.11.13
A.exists: true
/home/me/node_modules/co/index.js:292
    throw err;
          ^
TypeError: You may only yield a function, promise, generator, array, or object, but the following was passed: "undefined"
  at next (/home/me/node_modules/co/index.js:106:12)
  at /home/me/node_modules/co/index.js:45:5
  at next (/home/me/node_modules/co/index.js:90:21)
  at /home/me/node_modules/co/index.js:93:18
  at Immediate._onImmediate (/home/me/node_modules/co/index.js:52:14)
  at processImmediate [as _immediateCallback] (timers.js:374:17)
```

While

``` coffeescript
class A

  constructor: ->
    @exists = true
    console.log "A.exists: #{@exists}"

class B extends A

  constructor: ->
    super()

  printExists: ->
    console.log "B.exists: #{@exists}"

a = new A()
b = new B()
b.printExists()
```

Results in

```
$ coffee test51.coffee 
Running node v0.11.13
A.exists: true
A.exists: true
B.exists: true
```

**Comment by GeoffreyBooth** [comment]
This is impossible in CS2 / ES2015:

```bash
test.coffee:6:3: error: Class constructor may not be a generator
  constructor: ->
  ^^^^^^^^^^^
```
