### ISSUE TITLE
invalid message when compiling broken coffee file

### ISSUE THREAD

**Issue by socketpair** [jashkenas/coffeescript#3799]
```
$ cat bad.coffee 
qwe[:-1]
$ coffee -c bad.coffee 
Error: In bad.coffee, Parse error on line 1: Unexpected '{'
    at Object.parseError (/usr/lib/coffee-script/lib/coffee-script/parser.js:477:11)
    at Object.parse (/usr/lib/coffee-script/lib/coffee-script/parser.js:554:22)
    at Object.exports.compile.compile (/usr/lib/coffee-script/lib/coffee-script/coffee-script.js:47:20)
    at compileScript (/usr/lib/coffee-script/lib/coffee-script/command.js:182:33)
    at /usr/lib/coffee-script/lib/coffee-script/command.js:152:18
    at fs.js:271:14
    at Object.oncomplete (fs.js:107:15)
$ coffee --version
CoffeeScript version 1.4.0
```
Unexpected ``{`` ?!

**Comment by lydell** [comment]
Why didn’t you try the latest version?

```
$ coffee -v && coffee -bpe 'qwe[:-1]'
CoffeeScript version 1.8.0
[stdin]:1:5: error: unexpected :
qwe[:-1]
    ^
```

**Comment by socketpair** [comment]
It's linux mint baby :)
