### ISSUE TITLE
`TypeError` occurred whenever call `eval` on io.js 1.0.*

### ISSUE THREAD

**Issue by jacobbubu** [jashkenas/coffeescript#3810]
``` coffee
coffee = require 'coffee-script'
console.log coffee.eval '1+1'
```

```
TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
  at Object.exports.eval (/Users/shenrong/tmp/coffeeeval/node_modules/coffee-script/lib/coffee-script/coffee-script.js:162:34)
  at Object.<anonymous> (/Users/shenrong/tmp/coffeeeval/index.coffee:2:13)
  at Object.<anonymous> (/Users/shenrong/tmp/coffeeeval/index.coffee:1:1)
...
```

**Comment by jashkenas** [comment]
I'm not seeing this problem. `coffee.eval` is working alright on iojs 1.0.4 for me.

**Comment by jacobbubu** [comment]
I'm on MacOS Yosemite 10.10.2, using npm version(1.8) of coffee. It appeals on 1.9 too with  subtle changes on error stack:

```
TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
  at Object.exports.eval (/Users/shenrong/tmp/coffeeeval/node_modules/coffee-script/lib/coffee-script/coffee-script.js:176:34)
  at Object.<anonymous> (/Users/shenrong/tmp/coffeeeval/index.coffee:2:13)
  at Object.<anonymous> (/Users/shenrong/tmp/coffeeeval/index.coffee:1:1)
  at Module._compile (module.js:446:26)
...
```

**Comment by jashkenas** [comment]
How about with the latest version of io.js, and the latest (1.9) version of CoffeeScript?

**Comment by jacobbubu** [comment]
Has the same issue with the latest op.js (1.0.4) and CoffeeScript(1.9).

**Comment by jacobbubu** [comment]
The exception should be thrown by https://github.com/jashkenas/coffeescript/blob/master/src/coffee-script.coffee#L158

**Comment by GeoffreyBooth** [comment]
Saving the example as `test.coffee` and running `coffee test.coffee` in CS2 under Node 7.9.0 returns `2`.
