### ISSUE TITLE
`coffee --nodejs --use_strict` don't work

### ISSUE THREAD

**Issue by yuukinajima** [jashkenas/coffeescript#3874]
I got this error on `coffee --nodejs --use_strict`
```bash
% coffee -v
CoffeeScript version 1.9.1

% coffee --nodejs --use_strict                                                                                                   
child_process: customFds option is deprecated, use stdio instead.
/usr/local/lib/node_modules/coffee-script/lib/coffee-script/parser.js:590
        function lex() {
        ^^^^^^^^
SyntaxError: In strict mode code, functions can only be declared at top level or immediately within another function.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:15:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:373:4)
    at Module._compile (module.js:460:26)
```

**Comment by michaelficarra** [comment]
You'll have to take it up with Jison. This is a generated file.
