### ISSUE TITLE
space before postfix ++ causes failure

### ISSUE THREAD

**Issue by mortonfox** [jashkenas/coffeescript#3887]
The space character shouldn't matter but it appears that ```a ++``` now fails in CoffeeScript 1.9.1.

    $ coffee --version
    CoffeeScript version 1.9.1
    $ coffee
    coffee> a = 1
    1
    coffee> a++
    1
    coffee> a ++
    TypeError: undefined is not a function
      at SyntaxError.syntaxErrorToString [as toString] (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/helpers.js:216:26)
      at Object.exports.updateSyntaxError (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/helpers.js:198:27)
      at Object.nodes (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:37:23)
      at REPLServer.replDefaults.eval (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/repl.js:39:28)
      at bound (domain.js:254:14)
      at REPLServer.runBound [as eval] (domain.js:267:12)
      at repl.js:279:12
      at REPLServer.<anonymous> (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/repl.js:79:9)
      at REPLServer.emit (events.js:129:20)
      at REPLServer.Interface._onLine (readline.js:214:10)
      at REPLServer.Interface._line (readline.js:553:8)
      at REPLServer.Interface._ttyWrite (readline.js:830:14)
      at ReadStream.onkeypress (readline.js:109:10)
      at ReadStream.emit (events.js:129:20)
      at readline.js:1175:14
      at Array.forEach (native)
      at emitKeys (readline.js:993:10)
      at ReadStream.onData (readline.js:910:14)
      at ReadStream.emit (events.js:107:17)
      at readableAddChunk (_stream_readable.js:163:16)
      at ReadStream.Readable.push (_stream_readable.js:126:10)
      at TTY.onread (net.js:529:20)
    
    coffee>

**Comment by jashkenas** [comment]
The Rewriter is mistakenly trying to turn this into a function call instead of leaving it alone...

    coffee -te "a ++"
    [IDENTIFIER a] [CALL_START (] [++ ++] [CALL_END )] [TERMINATOR \n]

**Comment by lydell** [comment]
There’s nothing wrong with the `++` operator:

```
$ ./bin/coffee -bpe 'a ++'
[stdin]:1:5: error: unexpected end of input
a ++
    ^
```

The only problem is the repl. In fact, any parsing error breaks in it, while lexing errors and compilation errors work fine:

```
./bin/coffee
coffee> lexing error (
[stdin]:1:14: error: missing )
lexing error (
             ^
coffee> parsing error !
TypeError: undefined is not a function
  at SyntaxError.syntaxErrorToString [as toString] (/home/lydell/forks/coffee-script/lib/coffee-script/helpers.js:216:26)
coffee> compilation error @a:1
[stdin]:1:19: error: Invalid object key
compilation error @a:1
                  ^^
```

This is because the second parameter signature (`(tokens, options)` as opposed to `(code, options)` added in commit 1a9a48c) of `CoffeeScript.nodes` wasn’t considered when `withPrettyErrors` was added in commit 3f9cdcf1. `withPrettyErrors` assumes the `(code, options)` signature.

The repl bug was introduced in commit 8ed691 where we switched from passing a string of code to `CoffeeScript.nodes` to passing an array of tokens. A hotfix is to change the word `tokens` into `input` in https://github.com/jashkenas/coffeescript/blob/1e62781759e8497853072d9c17c25a9d4a4c42da/src/repl.coffee#L30. That works, but it is a bit ugly to lex the code twice.

The proper thing to do is to fix `CoffeeScript.nodes(tokens, options)`. The only thing I can think of is to make `withPrettyErrors(code, options)` _not_ trying prettify errors when `code` isn’t a string. When passing a non-string (ie an array of tokens) we could make it possible to pass `options.code` (or perhaps `options.input`) and `withPrettyErrors` could then use _that_ to prettify the errors instead. If so, we could change https://github.com/jashkenas/coffeescript/blob/1e62781759e8497853072d9c17c25a9d4a4c42da/src/repl.coffee#L30 into:

```coffee
ast = CoffeeScript.nodes tokens, code: input
```

I guess the above is the most sane thing to do, and it should be backwards-compatible as well. What do you think?

**Comment by lydell** [comment]
Or perhaps this is the simplest thing to do:

```
diff --git a/src/coffee-script.coffee b/src/coffee-script.coffee
index 7e6f76c..2a3033d 100644
--- a/src/coffee-script.coffee
+++ b/src/coffee-script.coffee
@@ -26,6 +26,7 @@ withPrettyErrors = (fn) ->
     try
       fn.call @, code, options
     catch err
+      throw err if typeof code isnt 'string'
       throw helpers.updateSyntaxError err, code, options.filename
 ```

That fixes the repl errors. We still get pretty error messages, because `updateSyntaxError` is called in https://github.com/jashkenas/coffeescript/blob/1e62781759e8497853072d9c17c25a9d4a4c42da/src/repl.coffee#L39 (using `input`).

That does not allow to be able to get pretty errors from `CoffeeScript.nodes(tokens)` as a consumer of the public API, but perhaps that doesn’t matter?
