### ISSUE TITLE
Encoding bug on node v0.12

### ISSUE THREAD

**Issue by ysmood** [jashkenas/coffeescript#3896]
To reproduce the bug, we need two files, and the node version should be v0.12. `io.js` has the same problem.

File `a.js`:

``` javascript
var abc = function abc() {
  return abc;
};

module.exports = abc;
```

File `b.coffee`

``` coffee
'测试'

abc = {}

require('./a')()
```

Run `coffee b.coffee`, you'll see the bug. If you run it with compiled coffee, such as `node b.js`, everything will goes well. I have no idea why it happens, it seems like a bug of V8, but only appears when using coffee.

The error info is:

```
ReferenceError: abc is not defined
  at abc (a.js:3:12)
  at Object.<anonymous> (b.coffee:5:1)
  at Object.<anonymous> (b.coffee:1:1)
  at Module._compile (module.js:460:26)
```

**Comment by cvlmtg** [comment]
I think I hit the same problem:

package.json
```
{
  "name": "test",
  "private": true,
  "dependencies": {
    "bull": "~0.2.7"
  }
}
```

b.coffee
```
Queue = require 'bull'
queue = Queue 'whatever', 6397, '127.0.0.1'
# this letter is important -> ì <-
console.log 'all ok'
process.exit()
```

```
$ node --version
v0.10.38
$ coffee b.coffee
all ok
$ nvf local 0.12.2
Using node version 0.12.2
$ node --version
v0.12.2
 $ coffee b.coffee
ReferenceError: Queue is not defined
  at Queue (/private/tmp/test/node_modules/bull/lib/queue.js:50:24)
  at Object.<anonymous> (/private/tmp/test/b.coffee:2:9)
  at Object.<anonymous> (/private/tmp/test/b.coffee:1:1)
  at Module._compile (module.js:460:26)
  at Object.exports.run (/Users/matteo/.nvf/installed/0.12.2/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:131:23)
  at compileScript (/Users/matteo/.nvf/installed/0.12.2/lib/node_modules/coffee-script/lib/coffee-script/command.js:224:29)
  at compilePath (/Users/matteo/.nvf/installed/0.12.2/lib/node_modules/coffee-script/lib/coffee-script/command.js:174:14)
  at Object.exports.run (/Users/matteo/.nvf/installed/0.12.2/lib/node_modules/coffee-script/lib/coffee-script/command.js:98:20)
  at Object.<anonymous> (/Users/matteo/.nvf/installed/0.12.2/lib/node_modules/coffee-script/bin/coffee:7:41)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3
```

now let's remove the letter *ì* from the comment

```
$ cat c.coffee
Queue = require 'bull'
queue = Queue 'whatever', 6397, '127.0.0.1'
# the letter was important
console.log 'all ok'
process.exit()
$ node --version
v0.12.2
$ coffee c.coffee
all ok
```

I'm on OSX 10.10.3, with coffee-script 1.9.2 and the coffee file should be a valid utf-8 (written with vim).

**Comment by GeoffreyBooth** [comment]
The `coffee` command is intended for compiling and debugging, not for running scripts as a replacement for the `node` command. A fix for this would be welcome, but our scope for the `coffee` command is not to handle all possible edge cases that `node` takes care of.
