### ISSUE TITLE
`assert` in REPL on Mac OS X

### ISSUE THREAD

**Issue by zhanzhenzhen** [jashkenas/coffeescript#3930]
CoffeeScript 1.9.1
Node.js 0.12.2
Mac OS X Yosemite 10.10.2

This problem only occurs on Mac OS X, not on Windows.

After you type this in coffee REPL:

```
assert(false)
```

It will throw an exception as expected, but then if you press the up-arrow key, it will not display the previous command, but will mistakenly show a `^[[A`. Here are the details:

```
coffee> assert(false)

assert.js:86
  throw new assert.AssertionError({
        ^
AssertionError: false == true
  at repl:1:5
  at Object.exports.runInThisContext (vm.js:74:17)
  at REPLServer.replDefaults.eval (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/repl.js:46:42)
  at bound (domain.js:254:14)
  at REPLServer.runBound [as eval] (domain.js:267:12)
  at repl.js:279:12
  at REPLServer.<anonymous> (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/repl.js:79:9)
  at REPLServer.emit (events.js:129:20)
  at REPLServer.Interface._onLine (readline.js:214:10)
  at REPLServer.Interface._line (readline.js:553:8)
  at REPLServer.Interface._ttyWrite (readline.js:830:14)
  at ReadStream.onkeypress (readline.js:109:10)
  at ReadStream.emit (events.js:129:20)
  at readline.js:1175:14
  at Array.forEach (native)
  at emitKeys (readline.js:993:10)
  at ReadStream.onData (readline.js:910:14)
  at ReadStream.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:163:16)
  at ReadStream.Readable.push (_stream_readable.js:126:10)
  at TTY.onread (net.js:538:20)

coffee> ^[[A^[[A^[[A^[[A^[[A
```

This problem only occurs after you use `assert` in coffee REPL. Other exceptions work correctly. Using `assert` in Node REPL also works correctly.

**Comment by GeoffreyBooth** [comment]
Tried to reproduce in 2.0.0-beta1 in Node 7.9.0 and I saw `assert(false)` in my history.
