### ISSUE TITLE
.coffeerc

### ISSUE THREAD

**Issue by ccorcos** [jashkenas/coffeescript#3987]
I'm curious if there is some way that I can configure my coffeescript REPL to require certain npm packages to variables when it starts. Something like a .bashrc file where I can write `ld = require 'lodash'`.

**Comment by jashkenas** [comment]
Check the changelog for the latest release.

> Added a Ruby-style -r option to the REPL, which allows requiring a module before execution with --eval or  --interactive.

**Comment by ccorcos** [comment]
Hmm. maybe i have to update it somehow

```
~ ❯❯❯ coffee -h                                                               

Usage: coffee [options] path/to/script.coffee -- [args]

If called without options, `coffee` will run your script.

  -b, --bare         compile without a top-level function wrapper
  -c, --compile      compile to JavaScript and save as .js files
  -e, --eval         pass a string from the command line as input
  -h, --help         display this help message
  -i, --interactive  run an interactive CoffeeScript REPL
  -j, --join         concatenate the source CoffeeScript before compiling
  -m, --map          generate source map and save as .js.map files
  -n, --nodes        print out the parse tree that the parser produces
      --nodejs       pass options directly to the "node" binary
      --no-header    suppress the "Generated by" header
  -o, --output       set the output directory for compiled JavaScript
  -p, --print        print out the compiled JavaScript
  -s, --stdio        listen for and compile scripts over stdio
  -l, --literate     treat stdio as literate style coffee-script
  -t, --tokens       print out the tokens that the lexer/rewriter produce
  -v, --version      display the version number
  -w, --watch        watch scripts for changes and rerun commands

~ ❯❯❯ coffee -r

/usr/local/lib/node_modules/coffee-script/lib/coffee-script/optparse.js:51
            throw new Error("unrecognized option: " + arg);
                  ^
Error: unrecognized option: -r
  at OptionParser.exports.OptionParser.OptionParser.parse (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/optparse.js:51:19)
  at parseOptions (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:512:29)
  at Object.exports.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:56:5)
  at Object.<anonymous> (/usr/local/lib/node_modules/coffee-script/bin/coffee:7:41)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:929:3
```

**Comment by ccorcos** [comment]
@jashkenas 

hey man, sorry to bug you, but how do I do this?

**Comment by connec** [comment]
Check your version (`coffee -v`), this was added in 1.9.2.

**Comment by ccorcos** [comment]
ahh. I kept doing `npm update -g coffeescript` instead of `npm update -g coffee-script`.

Thanks
