### ISSUE TITLE
Error: Cakefile not found in

### ISSUE THREAD

**Issue by kalashnikovisme** [jashkenas/coffeescript#4002]
``` shell
/home/username/coffeescript/lib/coffee-script/cake.js:111
    throw new Error("Cakefile not found in " + (process.cwd()));
          ^
Error: Cakefile not found in /home/username
  at cakefileDirectory (/home/username/coffeescript/lib/coffee-script/cake.js:111:11)
  at cakefileDirectory (/home/username/coffeescript/lib/coffee-script/cake.js:109:14)
  at cakefileDirectory (/home/username/coffeescript/lib/coffee-script/cake.js:109:14)
  at Object.exports.run (/home/username/coffeescript/lib/coffee-script/cake.js:51:19)
  at Object.<anonymous> (/home/username/coffeescript/bin/cake:7:38)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:906:3
```

I've just run everything like in `Readme`

``` shell
git clone https://github.com/jashkenas/coffeescript.git
sudo coffeescript/bin/cake install
```

What's wrong?

**Comment by geoidesic** [comment]
bump

**Comment by vendethiel** [comment]
cd into the directory to run bin/cake
