### ISSUE TITLE
CoffeeScript REPL calls Object.prototype.set() on defined property

### ISSUE THREAD

**Issue by Qix-** [jashkenas/coffeescript#4021]
Yeah that title was tricky to word. I'll just show you; I have no idea why/what/how is going on.

index.js:
~~~javascript
(function(X) {
  Object.defineProperty(
      Object.prototype,
      'X',
      {
        set: function(val) {
          console.log(val);
        }
      });
})(module
  ? module.exports
  : window.X = window.X ||{});
~~~

from the REPL:

~~~
/tmp$ coffee
coffee> X = require './' # index.js from above
{}
coffee> herp = {}
23
{}
coffee>
(^C again to quit)
coffee>
~~~

but not from the Node REPL:

~~~
/tmp$ node
> var X = require('./');
undefined
> herp = {}
{}
>
(^C again to quit)
>
~~~

For the record, I'm kind of sad it didn't return `42`.

**EDIT**: If this helps anyone, I threw a `console.trace()` in.

~~~
/tmp$ coffee
coffee> X = require './'
{}
coffee> herp= {}
23
Trace
  at Object.defineProperty.set (/private/tmp/index.js:8:19)
  at Scope.exports.Scope.Scope.add (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/scope.js:33:37)
  at Scope.exports.Scope.Scope.parameter (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/scope.js:60:19)
  at Block.exports.Block.Block.compileRoot (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:425:17)
  at Block.exports.Block.Block.compileToFragments (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:369:21)
  at Block.exports.Base.Base.compile (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:71:35)
  at REPLServer.replDefaults.eval (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/repl.js:41:18)
  at bound (domain.js:254:14)
  at REPLServer.runBound [as eval] (domain.js:267:12)
  at repl.js:279:12
  at REPLServer.<anonymous> (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/repl.js:79:9)
  at REPLServer.emit (events.js:129:20)
  at REPLServer.Interface._onLine (readline.js:214:10)
  at REPLServer.Interface._line (readline.js:553:8)
  at REPLServer.Interface._ttyWrite (readline.js:830:14)
  at ReadStream.onkeypress (readline.js:109:10)
  at ReadStream.emit (events.js:129:20)
  at readline.js:1175:14
  at Array.forEach (native)
  at emitKeys (readline.js:993:10)
  at ReadStream.onData (readline.js:910:14)
  at ReadStream.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:163:16)
  at ReadStream.Readable.push (_stream_readable.js:126:10)
  at TTY.onread (net.js:529:20)

{}
~~~

**Comment by Qix-** [comment]
Duh. It's *actually* setting `.X`. Go figure.
