### ISSUE TITLE
destructuring mis-documented and not working for parameters in 1.10

### ISSUE THREAD

**Issue by shaunc** [jashkenas/coffeescript#4098]
In the changelog you mention support for defaults in parameters:

    ({offsetHeight: height}) -> 

However, the PR supports with equals:

    {b = 1} = {}

which assigns 1 to b.

Unfortunately it doesn't seem to support parameter defaults at all, which was the original impetus:
```
coffee> foo = ({b = 1})->b
[Function]
coffee> foo()
repl:3
  b = (ref2 = arg.b) != null ? ref2 : 1;

TypeError: Cannot read property 'b' of undefined
  at foo (repl:3:18)
  at repl:1:5
  at Object.exports.runInThisContext (vm.js:74:17)
  at runInContext (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/repl.js:57:17)
  at REPLServer.replDefaults.eval (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/repl.js:46:25)
  at bound (domain.js:254:14)
  at REPLServer.runBound [as eval] (domain.js:267:12)
  at repl.js:279:12
  at REPLServer.<anonymous> (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/repl.js:86:9)
  at REPLServer.emit (events.js:129:20)
  at REPLServer.Interface._onLine (readline.js:214:10)
  at REPLServer.Interface._line (readline.js:553:8)
  at REPLServer.Interface._ttyWrite (readline.js:830:14)
  at ReadStream.onkeypress (readline.js:109:10)
  at ReadStream.emit (events.js:129:20)
  at readline.js:1175:14
  at Array.forEach (native)
  at emitKeys (readline.js:993:10)
  at ReadStream.onData (readline.js:910:14)
  at ReadStream.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:163:16)
  at ReadStream.Readable.push (_stream_readable.js:126:10)
  at TTY.onread (net.js:538:20)

```

**Comment by lydell** [comment]
>     ({offsetHeight: height}) ->

The above has worked in CoffeeScript for ages, and works exactly like in ES20125. It means:

```coffee
(node) ->
  height = node.offsetHeight
```

In other words, it is _not_ destructuring with defaults, it is destructuring with renaming.

> However, the PR supports with equals:
>
>     {b = 1} = {}

That's right. Just like ES2015, this is how you provide defaults to destructuring. You can do it with renaming, too:

```coffee
{offsetHeight: height = 0} = node
```

>     foo = ({b = 1})->b
>     foo()

The above has nothing to do with destructuring defaults. Even before CoffeeScript 1.10.0, the following gives the same error:

```coffee
foo = ({b})->b
foo()
```

That's because you're trying to destructure `undefined`. In both cases you need to add a _parameter default,_ just like in ES2015, eg:

```coffee
foo = ({b = 1} = {}) -> b
```

**Comment by shaunc** [comment]
Ah -- thank you for the detailed response! Sorry for the mistaken report.

I might venture to comment that the documentation is a bit unclear. :) ... does this `issues` track documentation bugs?

**Comment by lydell** [comment]
The easiest thing is actually to open a PR with your suggested changes (edit documentation/index.html.js). If it gets merged – great – otherwise not much work is lost.
