### ISSUE TITLE
Problem running tests in mocha when upgrading to coffee 1.10

### ISSUE THREAD

**Issue by dmoisset** [jashkenas/coffeescript#4103]
I have a test suite that started failing when I upgraded from coffee-script from 1.8.0 to 1.10.0. After reducing it to a minimal version, I got to this:

``` coffeescript
assert = require "assert"
sinon = require 'sinon'

suite 'break it', ->
    setup ->
        sinon.stub(Object, 'create')
    teardown -> null
    test "foo", -> assert.equal(1+1, 2)
```

I'm running this command: `mocha --ui tdd --compilers coffee:coffee-script/register test_broken.coffee` (`test_broken.coffee` is the file above). This is with mocha@2.0.1, sinon@1.11.1. 

The issue might be somehow related to the compiler registration code; If I compile the file manually with `coffee -c test_broken.coffee` and then run `mocha --ui tdd --compilers coffee:coffee-script/register test_broken.js` (i.e., I give mocha the precompiled file), the test runs and passes ok. 

Actually, I've tested other versions and the first one with problems is 1.9.0, 1.8.0 is the last one working ok

**Comment by vendethiel** [comment]
Do you have a difference of the compiled code before/after? Seems a bit surprising.

**Comment by lydell** [comment]
This sounds like an excellent case to use `git bisect run <cmd>`…

**Comment by dmoisset** [comment]
@vendethiel, No differences between both generated codes except for the obvious:

```diff
-// Generated by CoffeeScript 1.8.0
+// Generated by CoffeeScript 1.10.0
```

That also leads me to think that it's related to the compiler registration code somehow.

@lydell I might try that, but I don't have handy the environment to build different compiler versions and try it

**Comment by lydell** [comment]
@dmoisset you don't need to build anything. Every commit contains a built version of the compiler, ready to use. All you need is git and your test case.

**Comment by wi2** [comment]
Hello @dmoisset 
try with '='
like this : 
mocha --ui tdd --compilers=coffee:coffee-script/register test_broken.coffee

**Comment by dmoisset** [comment]
No difference between using '=' or not. In both cases the result is:

```


  break it
    1) "before each" hook


  0 passing (8ms)
  1 failing

  2) "after each" hook

  0 passing (13ms)
  2 failing


/home/dmoisset/norvig/aimara/tests_js/myenv/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:234
      throw helpers.updateSyntaxError(err, stripped, filename);
                    ^
TypeError: Cannot call method 'setInput' of undefined
  at Object.parse (/home/dmoisset/norvig/aimara/tests_js/myenv/lib/node_modules/coffee-script/lib/coffee-script/parser.js:584:11)
  at /home/dmoisset/norvig/aimara/tests_js/myenv/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:64:24
  at /home/dmoisset/norvig/aimara/tests_js/myenv/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:34:19
  at Object.exports._compileFile (/home/dmoisset/norvig/aimara/tests_js/myenv/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:227:16)
  at getSourceMap (/home/dmoisset/norvig/aimara/tests_js/myenv/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:343:22)
  at getSourceMapping (/home/dmoisset/norvig/aimara/tests_js/myenv/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:351:19)
  at formatSourcePosition (/home/dmoisset/norvig/aimara/tests_js/myenv/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:303:16)
  at /home/dmoisset/norvig/aimara/tests_js/myenv/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:369:33
  at Function.Error.prepareStackTrace (/home/dmoisset/norvig/aimara/tests_js/myenv/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:372:7)
  at /home/dmoisset/norvig/aimara/tests_js/myenv/lib/node_modules/mocha/lib/reporters/base.js:167:20
  at Array.forEach (native)
  at Function.exports.list (/home/dmoisset/norvig/aimara/tests_js/myenv/lib/node_modules/mocha/lib/reporters/base.js:158:12)
  at Spec.Base.epilogue (/home/dmoisset/norvig/aimara/tests_js/myenv/lib/node_modules/mocha/lib/reporters/base.js:311:10)
  at Runner.EventEmitter.emit (events.js:117:20)
  at Runner.uncaught (/home/dmoisset/norvig/aimara/tests_js/myenv/lib/node_modules/mocha/lib/runner.js:563:8)
  at process.uncaught (/home/dmoisset/norvig/aimara/tests_js/myenv/lib/node_modules/mocha/lib/runner.js:580:10)
  at process.EventEmitter.emit (events.js:95:17)
  at process._fatalException (node.js:272:26)
```

**Comment by wi2** [comment]
hi @dmoisset .

You right.. it's not the problem
I don't know why but now it's working for me when i remove '='

You probably ever did a lot of time : Try to uninstall coffee-script and reinstall it (dependencie and global).

So, 
why you parser is undefined..I don't have an idea... if me, i search about that first

I give you my config for comparing, maybe it's help you.. i hope.. good luck

my config:
node 4.2.1 and i try with node 0.12.7

"chai": "^3.3.0",
"coffee-script": "^1.10.0",
"mocha": "^2.3.3",

mocha.opts
```
--require coffee-script/register
--compilers coffee:coffee-script/register
--ui tdd
```

test.coffee
```javascript
chai  = require 'chai'
expect  = chai.expect

suite 'break it', ->
  setup ->
    console.log "setup"
  teardown -> null
  test "foo", -> expect(1+1).to.equal(2)
```



ps: sorry for my english..

**Comment by GeoffreyBooth** [comment]
I think this is out of our scope.
