### ISSUE TITLE
Maximum call stack size exceeded when compiling large code

### ISSUE THREAD

**Issue by andres-torres-marroquin** [jashkenas/coffeescript#4109]
Not a bug. Not a complaint. Just a heads up.

When you have an extraordinarily long code (> 10000 lines with multiple indentations), the compiler tends to fail. I have tried it on nodejs and Chrome, on both it fails, but it is easier to reproduce on nodejs, since v8 stack size is by default smaller than the Chrome one. I have reproduced this on 1.7 to 1.10 versions.

The example code to reproduce this is https://gist.github.com/andres-torres-marroquin/2abf7824e37a073820a9

Another way to reproduce this error is overriding the default stack size intentionally:
`coffee --nodejs --stack-size=50 -c file.coffee`

The error it throws to the console:

```
RangeError: Maximum call stack size exceeded
  at Call.exports.Call.Call.compileNode (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:999:24)
  at Call.exports.Base.Base.compileToFragments (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:83:21)
  at Parens.exports.Parens.Parens.compileNode (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:2665:24)
  at Parens.exports.Base.Base.compileToFragments (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:83:21)
  at Assign.exports.Assign.Assign.compileNode (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:1628:24)
  at Assign.exports.Base.Base.compileToFragments (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:83:21)
  at Class.exports.Class.Class.compileNode (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:1554:20)
  at Class.exports.Base.Base.compileToFragments (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:83:21)
  at Block.exports.Block.Block.compileNode (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:381:28)
  at Block.exports.Block.Block.compileWithDeclarations (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:474:19)
  at Code.exports.Code.Code.compileNode (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:1951:63)
  at Code.exports.Base.Base.compileToFragments (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:83:21)
  at Call.exports.Call.Call.compileNode (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:999:55)
  at Call.exports.Base.Base.compileToFragments (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:83:21)
  at Parens.exports.Parens.Parens.compileNode (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:2665:24)
  at Parens.exports.Base.Base.compileToFragments (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:83:21)
  at Assign.exports.Assign.Assign.compileNode (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:1628:24)
  at Assign.exports.Base.Base.compileToFragments (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:83:21)
  at Class.exports.Class.Class.compileNode (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:1554:20)
  at Class.exports.Base.Base.compileToFragments (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:83:21)
  at Block.exports.Block.Block.compileNode (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:381:28)
  at Block.exports.Block.Block.compileWithDeclarations (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:474:19)
  at Code.exports.Code.Code.compileNode (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:1951:63)
  at Code.exports.Base.Base.compileToFragments (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:83:21)
  at Call.exports.Call.Call.compileNode (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:999:55)
  at Call.exports.Base.Base.compileToFragments (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:83:21)
  at Parens.exports.Parens.Parens.compileNode (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:2665:24)
  at Parens.exports.Base.Base.compileToFragments (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:83:21)
  at Assign.exports.Assign.Assign.compileNode (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:1628:24)
  at Assign.exports.Base.Base.compileToFragments (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:83:21)
  at Class.exports.Class.Class.compileNode (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:1554:20)
  at Class.exports.Base.Base.compileToFragments (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:83:21)
  at Block.exports.Block.Block.compileNode (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:381:28)
  at Block.exports.Block.Block.compileWithDeclarations (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:474:19)
  at Code.exports.Code.Code.compileNode (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:1951:63)
  at Code.exports.Base.Base.compileToFragments (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:83:21)
  at Call.exports.Call.Call.compileNode (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:999:55)
  at Call.exports.Base.Base.compileToFragments (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:83:21)
  at Parens.exports.Parens.Parens.compileNode (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:2665:24)
  at Parens.exports.Base.Base.compileToFragments (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:83:21)
  at Assign.exports.Assign.Assign.compileNode (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:1628:24)
  at Assign.exports.Base.Base.compileToFragments (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:83:21)
  at Class.exports.Class.Class.compileNode (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:1554:20)
  at Class.exports.Base.Base.compileToFragments (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:83:21)
  at Return.exports.Return.Return.compileNode (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:653:48)
  at Return.exports.Base.Base.compileToFragments (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:83:21)
  at Return.exports.Return.Return.compileToFragments (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:644:52)
  at Block.exports.Block.Block.compileNode (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:381:28)
  at Block.exports.Block.Block.compileWithDeclarations (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:474:19)
  at Code.exports.Code.Code.compileNode (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:1951:63)
  at Code.exports.Base.Base.compileToFragments (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:83:21)
  at Block.exports.Block.Block.compileNode (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:381:28)
  at Block.exports.Block.Block.compileWithDeclarations (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:474:19)
  at Block.exports.Block.Block.compileRoot (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:446:24)
  at Block.exports.Block.Block.compileToFragments (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/nodes.js:363:21)
  at Object.<anonymous> (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:49:61)
  at Object.compile (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:34:19)
  at compileScript (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:216:33)
  at compilePath (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:161:14)
  at Object.exports.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:96:21)
  at Object.<anonymous> (/usr/local/lib/node_modules/coffee-script/bin/coffee:7:41)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:906:3
```

**Comment by vendethiel** [comment]
That makes sense, it's recursive... Is that an actual issue in production code, though?

**Comment by andres-torres-marroquin** [comment]
Yes, it is. Our solution will be splitting the code in the file to multiple files.

**Comment by rightfold** [comment]
[Obligatory.](https://vimeo.com/9981123)

**Comment by jashkenas** [comment]
> Yes, it is. Our solution will be splitting the code in the file to multiple files.

Is it hand-written CoffeeScript? Or are you machine-generating the source code?

**Comment by andres-torres-marroquin** [comment]
Hand-written. Don't yell at me please.

**Comment by jashkenas** [comment]
No yelling. That's just incredible. Is the compilation speed okay? It's just the level of nesting going deep enough that the recursion bottoms out?

**Comment by andres-torres-marroquin** [comment]
It takes about 25 seconds on with gulp (for production), and about 10 seconds on Chrome (for development). I think it isn't too nested, but it started to fail when we went over 12k LOCs, firstly on the with gulp, and after some more LOCs then with Chrome. The max indentation looks on 8 levels (32 spaces), but is commonly on 3 levels (12 spaces), also we're using requirejs, so 1 levels goes specifically to the module declaration.

I know that having one big file on a project is a bad practice, we have discussed this before multiple times, but we do like that we can minify the production file better, since everything is on the same context, it can minify the variable names to a very short version of them. Any of you guys, do you know how to keep that "minification style", and being able to split it down? I was thinking about concatenating CS-compiled files and the minifying but it seems wrong to me. Or maybe I'm trying to minify too much? 

Any suggestions are welcome.

**Comment by carlsmith** [comment]
I'm not sure about the best way, but I just split a big file up yesterday,  and it seemed easier to  concat the CoffeeScript source and compile the whole lot as one, than to concat the output of the compilations. Unless the file becomes super big, or someone explains a better way, concat-then-compile seems the least likey to confuse people and tools.

**Comment by borestad** [comment]
@andres-torres-marroquin: I felt so bad for your development workflow that I had to write something.

Split up your code with i.e webpack/browserify/require.js (with r.js) and finally GZIP the content on the server (with nginx/apache or whatever technology you choose). You'll find that gzipping will create a *much* better compression ratio than any minifier will ever do.

If you wan't to squeeze that extra out of the compression, you can use i.e https://github.com/pierreinglebert/node-zopfli

And yes, you're overthinking the minification :-)

**Comment by andres-torres-marroquin** [comment]
@borestad Thanks!. We have already splitted the code, we already use gzip, and we're minifying the code since we need to protect it.

**Comment by borestad** [comment]
Glad to hear! :-)

**Comment by GeoffreyBooth** [comment]
Not much the compiler can do to help with this, I’m afraid. Thanks for posting your workaround.
