### ISSUE TITLE
Comprehension error with gulp-browserify

### ISSUE THREAD

**Issue by noppanit** [jashkenas/coffeescript#4134]
I'm having a problem with the library. It's throwing.

```
Error: Parsing file /vagrant/node_modules/coffee-script/lib/coffee-script/lexer.js: Line 886: Comprehension Error
  at parseDeps (/vagrant/node_modules/module-deps/index.js:249:45)
  at done (/vagrant/node_modules/module-deps/index.js:229:13)
  at ap (/vagrant/node_modules/module-deps/index.js:202:42)
  at /vagrant/node_modules/module-deps/index.js:222:21
  at ConcatStream.<anonymous> (/vagrant/node_modules/concat-stream/index.js:36:43)
  at ConcatStream.emit (events.js:92:17)
  at finishMaybe (/vagrant/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:460:14)
  at afterWrite (/vagrant/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:340:3)
  at /vagrant/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:327:9
  at process._tickCallback (node.js:448:13)
```

Here's the line `886`
```
  JS_KEYWORDS = ['true', 'false', 'null', 'this', 'new', 'delete', 'typeof', 'in', 'instanceof', 'return', 'throw', 'break', 'continue', 'debugger', 'yield', 'if', 'else', 'switch', 'for', 'while', 'do', 'try', 'catch', 'finally', 'class', 'extends', 'super'];
```

I'm trying to build gulp-browserify with coffeescript.
Here's my gulp
```
	gulp.src('common/index.js')
		.pipe(browserify({
			transform: ['coffeeify']
		}))
		.pipe(gulp.dest('common/dist/scripts/habitrpg-shared.js'))
```

Here's my version
```
    "browserify": "~3.30.2",
    "coffee-script": "1.10.0",
    "coffeeify": "1.1.0",
```

**Comment by vendethiel** [comment]
I'm going to assume this was due to a problematic version/... and tag this as invalid
