### ISSUE TITLE
Unable to upgrade to Node 5.x

### ISSUE THREAD

**Issue by blacksonic** [jashkenas/coffeescript#4251]
Tried to upgrade my project from Node 4.x to 5.x and got the following error:

```
Error: Parse error on line 49: Unexpected ','
    at Object.parseError (/home/blacksonic/workspace/trend-reporting-service/node_modules/coffee-script/lib/coffee-script/parser.js:477:11)
    at Object.parse (/home/blacksonic/workspace/trend-reporting-service/node_modules/coffee-script/lib/coffee-script/parser.js:554:22)
    at Object.exports.compile.compile [as compile] (/home/blacksonic/workspace/trend-reporting-service/node_modules/coffee-script/lib/coffee-script/coffee-script.js:43:20)
    at /home/blacksonic/workspace/trend-reporting-service/node_modules/karma-coffee-preprocessor/index.js:30:23
    at nextPreprocessor (/home/blacksonic/workspace/trend-reporting-service/node_modules/karma/lib/preprocessor.js:35:26)
    at /home/blacksonic/workspace/trend-reporting-service/node_modules/karma/lib/preprocessor.js:114:9
    at module.exports (/home/blacksonic/workspace/trend-reporting-service/node_modules/isbinaryfile/index.js:28:12)
    at /home/blacksonic/workspace/trend-reporting-service/node_modules/karma/lib/preprocessor.js:79:7
    at /home/blacksonic/workspace/trend-reporting-service/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
```

**Comment by amalrik** [comment]
Could you provide all steps you took in order to reproduce the error?
I'm node 5.7.0 and i have no problems using coffeescript. So i guess is something with your environment.

**Comment by blacksonic** [comment]
I'm using it with latest karma-coffee-preprocessor and latest Node version 5.10.1
