### ISSUE TITLE
Error: Use CoffeeScript.register() or require the coffee-script/register module to require .coffee.md files.

### ISSUE THREAD

**Issue by malford89** [jashkenas/coffeescript#4282]
Hello, I am following along with a video to use a roots template with contentful. You can find the video here: https://www.youtube.com/watch?v=RzLw2pQXAsk. So after running "roots watch" in the terminal I get this error: 
`Michaels-MBP:contentful-test-blog michaelalford$ roots watch
/usr/local/lib/node_modules/roots-static/node_modules/coffee-script/lib/coffee-script/coffee-script.js:213
          throw new Error("Use CoffeeScript.register() or require the coffee-script/register module to require " + ext + " files.");
          ^

Error: Use CoffeeScript.register() or require the coffee-script/register module to require .coffee.md files.
  at Object.base.(anonymous function) [as .coffee] (/usr/local/lib/node_modules/roots-static/node_modules/coffee-script/lib/coffee-script/coffee-script.js:213:17)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at configure (/usr/local/lib/node_modules/roots-static/lib/commands/configure.js:16:34)
  at Object.module.exports [as configure] (/usr/local/lib/node_modules/roots-static/lib/commands/configure.js:66:5)
  at Object.<anonymous> (/usr/local/lib/node_modules/roots-static/bin/roots:13:14)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Function.Module.runMain (module.js:441:10)
  at startup (node.js:139:18)
  at node.js:968:3
`

I have little experience with coffeescript and connecting contentful to a website so I could use some guidance. After checking my project files I do see `require('./lib/coffee-script/register');` in register.js. Not sure what the problem is.

**Comment by vendethiel** [comment]
The one you found comes from CoffeeScript's files, not yours. Seems like Contentful or Roots are not up-to-date with CS 1.7.0, which dates back from JANUARY 28, 2014 ...

**Comment by malford89** [comment]
Sorry for my misunderstanding. When you say "them" do you mean Contentful or roots?
