### ISSUE TITLE
[CS2] Unexpected token import

### ISSUE THREAD

**Issue by MelvIsntNormal** [jashkenas/coffeescript#4482]
I'm trying to use webpack with CS 2:
```coffeescript
import * as path from 'path'

export default {
  entry: 'app/assets/scripts/main.coffee'
  output:
    path: path.resolve __dirname, 'public'
    filename: 'app.js'

  module:
    rules: [
      test: /\.(lit)?coffee$/, use: 'coffee-loader'
    ]
}
```

When webpack complained about this, I thought that maybe CS 2 wasn't supported yet. THen I ran that code through `coffee` on my machine:
```
<project directory>/webpack.config.coffee:1
(function (exports, require, module, __filename, __dirname) { import * as path from 'path';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.exports.run (/usr/lib/node_modules/coffeescript/lib/coffeescript/coffeescript.js:167:23)
    at compileScript (/usr/lib/node_modules/coffeescript/lib/coffeescript/command.js:221:29)
    at compilePath (/usr/lib/node_modules/coffeescript/lib/coffeescript/command.js:174:14)
    at Object.exports.run (/usr/lib/node_modules/coffeescript/lib/coffeescript/command.js:98:20)
    at Object.<anonymous> (/usr/lib/node_modules/coffeescript/bin/coffee:7:40)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3
```

I've tried searching issues and Google for the problem, but couldn't find anything. Am I using `import` incorrectly or something?

**Comment by GeoffreyBooth** [comment]
The Node runtime doesn’t support `import` yet. You need to pass the coffee output through Babel or some other tool to resolve modules. http://coffeescript.org/v2/#coffeescript-2
