### ISSUE TITLE
Tests failing on node v4.x

### ISSUE THREAD

**Issue by MylesBorins** [jashkenas/coffeescript#4610]
Seems like you are using a RegExp feature that is not supported in v4.x

The failure is caused by the test found on line 290 of `test/regexps.coffee` 

```
failed 1 and passed 852 tests in 3.70 seconds

  #4248: Unicode code point escapes
  SyntaxError: Invalid flags supplied to RegExp constructor 'u'
    at new RegExp (native)
    at Function.<anonymous> (/Users/mborins/code/coffeescript/test/regexps.coffee:1:1)
    at global.test (/Users/mborins/code/coffeescript/Cakefile:1:1)
    at Object.<anonymous> (/Users/mborins/code/coffeescript/test/regexps.coffee:1:1)
    at Object.<anonymous> (/Users/mborins/code/coffeescript/test/regexps.coffee:1:1)
    at Module._compile (module.js:1:1)
    at Object.exports.run (/Users/mborins/code/coffeescript/lib/coffee-script/coffee-script.js:1:1)
    at runTests (/Users/mborins/code/coffeescript/Cakefile:1:1)
    at Object.action (/Users/mborins/code/coffeescript/Cakefile:1:1)
    at helpers.extend.invoke (/Users/mborins/code/coffeescript/lib/coffee-script/cake.js:1:1)
    at Object.exports.run (/Users/mborins/code/coffeescript/lib/coffee-script/cake.js:1:1)
    at Object.<anonymous> (/Users/mborins/code/coffeescript/bin/cake:1:1)
    at Module._compile (module.js:1:1)
    at Object.Module._extensions..js (module.js:1:1)
    at Module.load (module.js:1:1)
    at Function.Module._load (module.js:1:1)
    at Function.Module.runMain (module.js:1:1)
    at startup (node.js:1:1)
    at node.js:1:1
```

**Comment by GeoffreyBooth** [comment]
We don’t aim to have the tests succeed in Node 4. See #4502.

If you’d like to submit a PR that disables this test in Node versions below the version that supports unicode regexes, I would merge it, but the tests are assumed to be running in current latest Node.

**Comment by MylesBorins** [comment]
I've already disabled in our smoke testing suite... we will keep it disabled.

Node v4 is officially supported until April 2018... so it is possible other people will show up fairly confused.  I highly suggest updating the engines field in your package.json

**Comment by GeoffreyBooth** [comment]
Our `engines` field is `"node": ">=0.8.0"`. That refers to the compiler itself, what you get when you run `coffee`. If that isn’t true, that’s a bug and we will address it.

We’re close to releasing CoffeeScript 2, which will be Node >= 8.
