### ISSUE TITLE
[CS2] unexpected token (CLI)

### ISSUE THREAD

**Issue by coderofsalvation** [jashkenas/coffeescript#4676]
```
[sqz@localhost~/Downloads]  $ npm install coffeescript@next -g
/home/sqz/opt/nvm/versions/node/v6.9.1/bin/coffee -> /home/sqz/opt/nvm/versions/node/v6.9.1/lib/node_modules/coffeescript/bin/coffee
/home/sqz/opt/nvm/versions/node/v6.9.1/bin/cake -> /home/sqz/opt/nvm/versions/node/v6.9.1/lib/node_modules/coffeescript/bin/cake
/home/sqz/opt/nvm/versions/node/v6.9.1/lib
└── coffeescript@2.0.0-beta4 

[sqz@localhost~/Downloads]  $ coffee
/home/sqz/opt/nvm/versions/node/v6.9.1/lib/node_modules/coffeescript/lib/coffeescript/repl.js:29
    eval: async function(input, context, filename, cb) {
                ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.exports.run (/home/sqz/opt/nvm/versions/node/v6.9.1/lib/node_modules/coffeescript/lib/coffeescript/command.js:114:14)
    at Object.<anonymous> (/home/sqz/opt/nvm/versions/node/v6.9.1/lib/node_modules/coffeescript/bin/coffee:15:45)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

[sqz@localhost~/Downloads]  $ uname -a   
Linux localhost 3.18.0-15976-g75b344ab7870 #1 SMP PREEMPT Mon Aug 28 11:13:29 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
[sqz@localhost~/Downloads]  $ cat /etc/issue 
Ubuntu 16.04.2 LTS \n \l
```

**Comment by GeoffreyBooth** [comment]
This is because of #4604, which assumes Node 7.6+. If you upgrade to Node 8, that should solve your issue.

@connec should we put some kind of `if` on the async-in-REPL code so that it only loads on Node 7.6+?

**Comment by coderofsalvation** [comment]
ok thx. Not sure, but wasn't there a package.json-attribute to force a node-version?

**Comment by coderofsalvation** [comment]
it seems there is: https://stackoverflow.com/questions/29349684/how-can-i-specify-the-required-node-js-version-in-packages-json

**Comment by lydell** [comment]
@coderofsalvation We already have `{ "engines" : { "node" : ">=7.6 } }` in package.json. Unfortunately, npm (at least version 3) does not seem to give any kind of warning when installing, though.

**Comment by GeoffreyBooth** [comment]
Closing as this isn’t really a bug, but after #4679 the `coffee` command should work in Node 6 too.
