### ISSUE TITLE
Bug: "coffee -b " is erroring over the "window" variable. 

### ISSUE THREAD

**Issue by chausies** [jashkenas/coffeescript#5141]
```coffee
query = window.location.search.substring(1).split('&')
```

Put that code in `test.coffee`. Then, when I run `coffee -b test.coffee`, it errors out, saying "window is not defined". It compiles totally fine for `coffee -c test.coffee`, but it goes wonky for the bare compilation.
Here's the full error message.
```
ReferenceError: window is not defined
  at Object.<anonymous> (/THIS/IS/THE/PATH/TO/test.coffee:1:1)
  at Module._compile (module.js:410:26)
  at Object.exports.run (/usr/lib/coffee-script/lib/coffee-script/coffee-script.js:134:23)
  at compileScript (/usr/lib/coffee-script/lib/coffee-script/command.js:224:29)
  at compilePath (/usr/lib/coffee-script/lib/coffee-script/command.js:174:14)
  at Object.exports.run (/usr/lib/coffee-script/lib/coffee-script/command.js:98:20)
  at Object.<anonymous> (/usr/lib/coffee-script/bin/coffee:7:41)
  at Module._compile (module.js:410:26)
  at Object.Module._extensions..js (module.js:417:10)
  at Module.load (module.js:344:32)
  at Function.Module._load (module.js:301:12)
  at Function.Module.runMain (module.js:442:10)
  at startup (node.js:136:18)
  at node.js:966:3
```

* CoffeeScript version: 1.9.3
* Node.js version: 4.2.6

**Comment by vendethiel** [comment]
`-b` is not bare compilation -- `-bc` is.

**Comment by chausies** [comment]
@ven

> 
> 
> `-b` is not bare compilation -- `-bc` is.

Got it. But then the `coffee -h` help message should be updated. Currently, it reads
```
terminal$ coffee -h

Usage: coffee [options] path/to/script.coffee -- [args]

If called without options, `coffee` will run your script.

  -b, --bare         compile without a top-level function wrapper
  -c, --compile      compile to JavaScript and save as .js files
```
According to that, it seems extremely easy to think that -b is to be used exactly like -c.
