### ISSUE TITLE
Proposal: allow more cakefile names, like rake

### ISSUE THREAD

**Issue by jethrodaniel** [jashkenas/coffeescript#5312]
Coming from a Ruby background, I was surprised that `cakefile` isn't allowed - cakefiles must be capitalized, i.e, `Cakefile`.

### Expected Behavior

Allow for alternate cakefile names, similar to `rake`, i.e, `Cakefile`, `cakefile`, `Cakefile.coffee`, `cakefile.coffee`.

### Current Behavior

Currently, having a `cakefile` is the same as **not** having a `Cakefile`.

```
$ cake
/path/to/code/node_modules/coffeescript/lib/coffeescript/cake.js:132
    throw new Error(`Cakefile not found in ${process.cwd()}`);
    ^

Error: Cakefile not found in /path/to/code
    at cakefileDirectory (/path/to/code/node_modules/coffeescript/lib/coffeescript/cake.js:132:11)
    at cakefileDirectory (/path/to/code/node_modules/coffeescript/lib/coffeescript/cake.js:130:14)
    at cakefileDirectory (/path/to/code/node_modules/coffeescript/lib/coffeescript/cake.js:130:14)
    at cakefileDirectory (/path/to/code/node_modules/coffeescript/lib/coffeescript/cake.js:130:14)
    at cakefileDirectory (/path/to/code/node_modules/coffeescript/lib/coffeescript/cake.js:130:14)
    at cakefileDirectory (/path/to/code/node_modules/coffeescript/lib/coffeescript/cake.js:130:14)
    at Object.exports.run (/path/to/code/node_modules/coffeescript/lib/coffeescript/cake.js:68:19)
    at Object.<anonymous> (/home/user/.config/yarn/global/node_modules/coffeescript/bin/cake:22:42)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
$ mv cakefile Cakefile
$ cake
Cakefile defines the following tasks:

cake build                # Build project from coffeescript -> js
cake start                # start react app
cake deploy               # deploy this gh-pages site
cake test                 # run the tests
cake serve                # run the local server
```

### Possible Solution

Simply look for those other filenames as well, and select the first one found as the cakefile.

We could also error out if more than one cakefile name is found (for example, if `cakefile` and `Cakefile` are present). I'm partial to this approach, as I think it's more expected. Worth noting that `rake` takes the _select the first one_ approach here.

### Environment

```
$ coffee --version
CoffeeScript version 2.5.1
```

**Comment by ahmedkhan1** [comment]
CoffeeScript variable names are case-sensitive. so cakeFile and CakeFile will be different. Do you want to change the variable case sensitivity?

**Comment by jethrodaniel** [comment]
Not at all. This is just about making the `cake` command support cakefiles named `cakefile` (lowercase) in addition to `Cakefile`.

**Comment by Inve1951** [comment]
Just use Windows. /s

**Comment by GeoffreyBooth** [comment]
You can always run via `coffee cakefile`. Closing as `Cakefile` is basically a file extension like `Dockerfile` and introducing a new file extension has ecosystem repercussions.
