### ISSUE TITLE
crash with typeof 10n

### ISSUE THREAD

**Issue by MarcoCostantini** [jashkenas/coffeescript#5321]
```
kubuntu@kubuntu:~/prog$ node -v
v10.19.0
kubuntu@kubuntu:~/prog$ node
> typeof 10n
'bigint'
> 
kubuntu@kubuntu:~/prog$ coffee -v
CoffeeScript version 1.8.0
kubuntu@kubuntu:~/prog$ coffee 
coffee> typeof 10n
Thrown:
{ [[stdin]:1:10: error: unexpected n
typeof 10n
         ^]
  location:
   { first_line: 0, first_column: 9, last_line: 0, last_column: 9 },
  toString: [Function: syntaxErrorToString],
  code: 'typeof 10n\n',
  filename: undefined }
coffee> readline.js:1086
            throw err;
            ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
  at maybeCallback (fs.js:128:9)
  at Object.write (fs.js:540:14)
  at REPLServer.<anonymous> (/home/kubuntu/prog/node_modules/coffee-script/lib/coffee-script/repl.js:121:12)
  at REPLServer.emit (events.js:203:15)
  at REPLServer.EventEmitter.emit (domain.js:448:20)
  at REPLServer.Interface._onLine (readline.js:308:10)
  at REPLServer.Interface._line (readline.js:656:8)
  at REPLServer.Interface._ttyWrite (readline.js:937:14)
  at REPLServer.self._ttyWrite (repl.js:715:7)
  at ReadStream.onkeypress (readline.js:184:10)
  at ReadStream.emit (events.js:203:15)
  at ReadStream.EventEmitter.emit (domain.js:448:20)
  at emitKeys (internal/readline.js:424:14)
  at emitKeys.next (<anonymous>:null:null)
  at ReadStream.onData (readline.js:1073:36)
  at ReadStream.emit (events.js:198:13)
  at ReadStream.EventEmitter.emit (domain.js:448:20)
  at addChunk (_stream_readable.js:288:12)
  at readableAddChunk (_stream_readable.js:269:11)
  at ReadStream.Readable.push (_stream_readable.js:224:10)
  at TTY.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

kubuntu@kubuntu:~/prog$ 
```

**Comment by GeoffreyBooth** [comment]
> `CoffeeScript version 1.8.0`

The current version is 2.5.1, and BigInt is supported.
